global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
    cluster: 'pulsar-cluster-1'

scrape_configs:

  - job_name: "proxy"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '127.0.0.1:8080'

  - job_name: "broker"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '127.0.0.1:8080'

  - job_name: "bookie"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '127.0.0.1:8000'

  - job_name: "zookeeper"
    honor_labels: true
    static_configs:
    - targets: 
      - '127.0.0.1:7001'
 
  - job_name: "node"
    static_configs:
    - targets: 
      - '127.0.0.1:9100'

  - job_name: "raphtory"
    honor_labels: true
    static_configs:
    - targets:
      - '127.0.0.1:8899'
